
default:
	abella type_uniqueness.thm -c type_uniqueness.thc
	abella less_precision.thm -c less_precision.thc
	abella auxiliary.thm -c auxiliary.thc
	abella progress.thm -c progress.thc
	abella preservation.thm -c preservation.thc
	abella blame_theorem.thm -c blame_theorem.thc
	abella nesting_theorems.thm -c nesting_theorems.thc
	abella catchup_theorems.thm -c catchup_theorems.thc
	abella unwrapping.thm -c unwrapping.thc
	abella gradual_guarantee.thm -c gradual_guarantee.thc
		
clean:
	rm *.thc


display_admitted:
	grep skip *
